### PR TITLE
Updates UI of repeated groups.

### PR DESCRIPTION
**Pull request by balazsracz**
If there is a plausible description field inside a repeated group, displays this field on the tab itself.

### CODE REVIEW

**Comment by pabender** [comment]
Balazs,

On Nov 26, 2016, at 12:13 PM, Balazs Racz <notifications@github.com> wrote:
> If there is a plausible description field inside a repeated group, displays this field on the tab itself.
> 
It is generally a bad idea to display a description on the tabs.  Descriptions are not necessarily short text, which is what you want as a tab name.  

The previous code set the tab name to the group name, to which the manufacturer has assigned meaning.  I think there is value in displaying that structural element within the tab.

The description elements already appear on the tabs, but If you want the descriptions accessible via the tabs, the can appear as tool tips.

Paul

**Comment by balazsracz** [comment]
yeah I think I was not particularly clear in the text of this PR. I'm not putting a manufacturer specified <description> into the tab title -- you're right that would be way too long and not useful either.

What I see is that the typical way people make their configuration spaces is that they put a user-editable text field inside the repeated group. This string field has no impact on the operation of the hardware; it's there for the user to "document" what they are doing, or what the physical connection of their hardware is.

This is there explicitly for the user to remind themselves on what they are doing. That reminder is what I put into the tab title.

Here is a screenshot for an imaginary siding controlled by a tower-lcc node:

image

The goal is to give an overview for the user so that they know and immediately understand where they need to click.

Generally if we only show this:
image
then the user has to guess, or memorize by heart which channel number does what.

**Comment by dpharris** [comment]
Perhaps if the description in the tab can be limited to some length, say 20
chars, and the entire description appear as a tooltip?

David

**Comment by balazsracz** [comment]
I'm not convinced there is an issue here to fix.
Did you look at the screenshot?

If you think there is a problem, please file an issue, that way we can
track, collect user feedback, and act on it. We should not act on a
misunderstanding.

**Pull request merged**
