### PR TITLE
Upgrades to CdiPanel configuration

### PR DESCRIPTION
**Pull request by petecressman**
Implement closing dialog to let user go back and write changes. Remind 
user to save panel when sensor or turnout is made. Enable/disable 'Write
All' button (formerly Save changes button) according to whether saves
are needed. Suppress 'end update' message when no changes have been
made. Fix create sensor/turnout titled panel. Set Collapse panels title
to bold.  Set default directory for backup and restore to user's choice
of file location in preferences.

### CODE REVIEW

**Comment by atanisoft** [comment]
There appears to be some whitespace consistency issues in the updated CdiPanel.java file. It would be good to clean this up prior to merge.

**Comment by pabender** [comment]
Closing and opening to see if the CI build runs.

**Comment by pabender** [comment]
There appears to be an issue with the configuration on Travis that crept up since the last PR on the repo.  Let me fix that so CI completes before we put this in.

**Comment by petecressman** [comment]
The problem might be with a mal-formed panel file that I have used as a negative test for some of my error checking in Circuit Builder.  (SignalMast with a bad system name). If this is the problem, I can delete the offending mast in the file.

**Comment by petecressman** [comment]
It's Apveyor with that problem.  I think CI needs me to do something about maven.  I will get to that soon.

**Comment by pabender** [comment]
@petecressman i checked the logs on Travis.  There is a configuration error there before it even gets to the maven build.

In other words, it isn’t even getting to maven to build your code.

**Comment by petecressman** [comment]
Withdraw this PR until those who asked me to do this have reviewed it.

**Pull request closed without merging**
