### PR TITLE
Use logging instead of dumping to STDERR or STDOUT

### PR DESCRIPTION
**Pull request by rhwood**
Use a java.util.logging.Logger in place of most uses of ``System.(err|out).println``` in the sources (but not in the tests) so that consuming applications (mostly JMRI) can manage logging. See JMRI/JMRI#3063

### CODE REVIEW

**Comment by rhwood** [comment]
In this case, I think the percent covered decreased only because the amount of coverable code decreased.

**Comment by pabender** [comment]
What I find interesting is that the coveralls check appears,  but the Travis one isn't, and it should be.  We know it ran, because that is how the coveralls check was triggered.

I'm going to close and re-open to see if that appears.

**Comment by rhwood** [comment]
@pabender Thanks; I hadn't clued into that.

**Comment by pabender** [comment]
Ok, tests area appearing now.  This is the first real commit since the test coverage was instituted.  I'm going to commit this, and hen I need to adjust the threshholds for failure on coveralls.

**Comment by pabender** [comment]
@rhwood, you snuck another change in here.

I want to get this committed before @balazsracz fixes the commit history, which is going to force us to rebate our local repositories.

**Comment by rhwood** [comment]
@pabender Go ahead and merge. I put a change that the first Travis CI build caught. Nothing more to add.

**Comment by balazsracz** [comment]
To the original topic of this commit: after we do logging, will the errors
appear on the JMRI console?

As for the rebase: I'm ready with the script; I can do whenever you guys
tell me you're ready.

**Comment by rhwood** [comment]
They will reliably appear, they will be controllable, so if someone wants debug level output, that can be turned on only for that user without a source code change. Dumping to STDOUT/ERR does *not* ensure the message is logged, as not all uses of the JMRI libraries capture that in output in logs.

**Comment by pabender** [comment]
Ok, merging.

**Comment by pabender** [comment]
@balazsracz go ahead and run the script when you can.

**Pull request merged**
