### PR TITLE
Build and publish using Maven

### PR DESCRIPTION
**Pull request by rhwood**
By building and publishing OpenLCB using Maven, other projects wishing to import this project can do using any package manager that can import packages from [Maven Central](most Java package managers can) and allow some IDEs to directly incorporate the project JavaDocs.

This PR allows, once the [Initial Setup](http://central.sonatype.org/pages/ossrh-guide.html) is complete, the OpenLCB JAR, sources, and JavaDocs to be published via Maven Central and the build report and JavaDocs to be published at https://openlcb.github.io/OpenLCB_Java using the following two commands and a git commit of pom.xml (assuming all tests pass):
```
mvn versions:set -DnewVersion=1.2.3
mvn clean deploy -P release
```

This would also mean that built artifacts (the doc directory, the openlcb.jar files) would not need to be stored in git (as they should not be).

After the initial setup, the Maven settings.xml file (```~/.m2/settings.xml``` on macOS or Linux) should read something like:
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>github</id>
      <password>RELEASERS-GITHUB-OAUTH-TOKEN</password>
    </server>
    <server>
      <id>ossrh</id>
      <username>RELEASERS-MAVEN-CENTRAL-USERNAME</username>
      <password>RELEASERS-MAVEN-CENTRAL-PASSWORD</password>
    </server>
  </servers>
  <profiles>
    <profile>
    <profile>
      <id>ossrh</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <gpg.executable>gpg2</gpg.executable>
        <gpg.passphrase>RELEASERS-MAVEN-CENTRAL-GPG-KEY-PASSPHRASE</gpg.passphrase>
      </properties>
    </profile>
  </profiles>
</settings>
```

### CODE REVIEW

**Comment by balazsracz** [comment]
sonatype ticket: https://issues.sonatype.org/browse/OSSRH-26367

**Comment by balazsracz** [comment]
I managed to get through all the hurdles of setting up the repository and signing and everything and I believe I completed the first release.

I will merge this and then apply the patches needed to get it working -- which are just javadoc fixes. Maven is very strict about javadoc.
@pabender  or @rhwood : Do you know how we can enable javadoc checking for the automated testing? I don't want anyone to commit stuff that triggers a javadoc warning.

Other qn @rhwood : I am very uneasy to have my password and PGP key passphrase in cleartext in a text file on my hard drive. Is there a way to omit them and either use an agent (like ssh-agent or gnome keyring), or a smartcard or yubikey device to hold the passwords and keys?

thanks for all the help, it would have taken me forever to piece together this complicated configuration,
Balazs

**Comment by rhwood** [comment]
@balazsracz

Re GPG: The maven release process should default to using gpg-agent if that's available. See http://stackoverflow.com/a/25197868/176160 for more information.

Re JavaDoc in PR: The default Travis tests deliberately do not generate JavaDocs, so you want to add something like ```script: mvn test site``` to your .travis.yml file

Also note that the process of pushing a "published" version is slightly different than pushing a snapshot (or nightly) version. I'll find the docs later.

**Comment by balazsracz** [comment]
@rhwood: thanks for the link, i'll try the agent. That sounds much better.

re: publishing. I think that it automatically detects whether the version ends with -SNAPSHOT and does different things. I have tested releasing both snapshot versions as well as non-snapshot, and the latter created and automatically graduated the repository.
It's just that the sonatype setup ticket has an additional round of configuration they say needs to be done. Something like "enable syncing to the central repository". So i'm waiting for them atm.

**Comment by pabender** [comment]
Sent from my iPad

On Nov 28, 2016, at 4:26 PM, Balazs Racz <notifications@github.com> wrote:

> I will merge this and then apply the patches needed to get it working -- which are just javadoc fixes. Maven is very strict about javadoc. @pabender or @rhwood : Do you know how we can enable javadoc checking for the automated testing? I don't want anyone to commit stuff that triggers a javadoc warning.
> 
It is another call in the build.  I can add that check tonight, after my daughter goes to sleep.

Paul

**Pull request merged**
